import { ProcessorTypes } from '../../propProcessors';
import AnchorElement from './anchor';
import FormElement from './form';
import InputElement from './input';
import BaseElement from './base';
import ImageElement from './image';
import LabelElement from './label';
import ButtonElement from './button';
import ListItemElement from './list-item';
import OListElement from './o-list';
import CanvasElement from './canvas';
import DataElement from './data';
import ModElement from './mod';
import DetailsElement from './details';
import StyleElement from './style';
import QuoteElement from './quote';
import SelectElement from './select';
import OptionElement from './option';
import OptionGroupElement from './option-group';
import WithChildren from './with/children';

export type Element = {
	accessKey?: HTMLElement['accessKey'];
	autocapitalize?:
		| ('off' | 'none')
		| ('on' | 'sentences')
		| 'words'
		| 'characters';
	autofocus?: HTMLElement['autofocus'];
	class?: HTMLElement['className'];
	contentEditable?: HTMLElement['contentEditable'];
	dir?: 'ltr' | 'rtl' | 'auto';
	draggable?: HTMLElement['draggable'];
	enterKeyHint?: HTMLElement['enterKeyHint'];
	hidden?: HTMLElement['hidden'];
	id?: HTMLElement['id'];
	inputMode?: HTMLElement['inputMode'];
	lang?: HTMLElement['lang'];
	nonce?: HTMLElement['nonce'];
	part?: HTMLElement['part'];
	slot?: HTMLElement['slot'];
	spellCheck?: HTMLElement['spellcheck'];
	tabIndex?: HTMLElement['tabIndex'];
	title?: HTMLElement['title'];
	translate?: HTMLElement['translate'];
} & {
	itemId?: string;
	itemProp?: string;
	itemRef?: string;
	itemScope?: string;
	itemType?: string;
} & {
	style?: ProcessorTypes['style'];
};

export type MutableElements = {
	a: AnchorElement;
	abbr: Element & WithChildren;
	address: Element & WithChildren;
	// area: AreaElement;
	article: Element & WithChildren;
	aside: Element & WithChildren;
	// audio: AudioElement;
	b: Element & WithChildren;
	base: BaseElement;
	bdi: Element & WithChildren;
	bdo: Element & WithChildren;
	// blockquote: QuoteElement;
	br: Element;
	button: ButtonElement;
	canvas: CanvasElement;
	// caption: TableCaptionElement;
	cite: Element & WithChildren;
	code: Element & WithChildren;
	// col: TableColElement;
	// colgroup: TableColElement;
	data: DataElement;
	// datalist: DataListElement;
	dd: Element & WithChildren;
	del: ModElement;
	details: DetailsElement;
	dfn: Element & WithChildren;
	div: Element & WithChildren;
	dl: Element & WithChildren;
	dt: Element & WithChildren;
	em: Element & WithChildren;
	// embed: EmbedElement;
	// fieldset: FieldSetElement;
	figcaption: Element & WithChildren;
	figure: Element & WithChildren;
	footer: Element & WithChildren;
	form: FormElement;
	h1: Element & WithChildren;
	h2: Element & WithChildren;
	h3: Element & WithChildren;
	h4: Element & WithChildren;
	h5: Element & WithChildren;
	h6: Element & WithChildren;
	header: Element & WithChildren;
	hgroup: Element & WithChildren;
	hr: Element;
	i: Element & WithChildren;
	// iframe: IFrameElement;
	img: ImageElement;
	input: InputElement;
	// ins: ModElement;
	kbd: Element & WithChildren;
	label: LabelElement;
	// legend: LegendElement;
	li: ListItemElement;
	// link: LinkElement;
	main: Element & WithChildren;
	// map: MapElement;
	mark: Element & WithChildren;
	// menu: MenuElement;
	// meta: MetaElement;
	// meter: MeterElement;
	nav: Element & WithChildren;
	noscript: Element & WithChildren;
	// object: ObjectElement;
	ol: OListElement;
	optgroup: OptionGroupElement;
	option: OptionElement;
	// output: OutputElement;
	p: Element & WithChildren;
	// param: ParamElement;
	// picture: PictureElement;
	pre: Element & WithChildren;
	// progress: ProgressElement;
	q: QuoteElement;
	rp: Element & WithChildren;
	rt: Element & WithChildren;
	ruby: Element & WithChildren;
	s: Element & WithChildren;
	samp: Element & WithChildren;
	// script: ScriptElement;
	section: Element & WithChildren;
	select: SelectElement;
	// slot: SlotElement;
	small: Element & WithChildren;
	// source: SourceElement;
	span: Element & WithChildren;
	strong: Element & WithChildren;
	style: StyleElement;
	sub: Element & WithChildren;
	summary: Element & WithChildren;
	sup: Element & WithChildren;
	// table: TableElement;
	// tbody: TableSectionElement;
	// td: TableCellElement;
	// template: TemplateElement;
	// textarea: TextAreaElement;
	// tfoot: TableSectionElement;
	// th: TableCellElement;
	// thead: TableSectionElement;
	// time: TimeElement;
	// title: TitleElement;
	// tr: TableRowElement;
	// track: TrackElement;
	u: Element & WithChildren;
	ul: Element & WithChildren;
	var: Element & WithChildren;
	// video: VideoElement;
	wbr: Element & WithChildren;
};

export default MutableElements;
