import {
	EventHandlers,
	ExtractMap,
	ExtractString,
	HTMLElementsMap,
} from '../types/_utils';

type SpecificEventHandlers<Tag extends keyof HTMLElementTagNameMap> = Exclude<
	keyof EventHandlers<HTMLElementTagNameMap[Tag]>,
	typeof htmlElementAttributes['*'][keyof typeof htmlElementAttributes['*']]
>;

type input = Exclude<
	keyof EventHandlers<HTMLElementTagNameMap['input']>,
	typeof htmlElementAttributes['*'][keyof typeof htmlElementAttributes['*']]
>;

const htmlElementAttributes = {
	'*': [
		'onauxclick',
		'onbeforematch',
		'onblur',
		'oncancel',
		'oncanplay',
		'oncanplaythrough',
		'onchange',
		'onclick',
		'onclose',
		'oncontextlost',
		'oncontextmenu',
		'oncontextrestored',
		'oncopy',
		'oncuechange',
		'oncut',
		'ondblclick',
		'ondrag',
		'ondragend',
		'ondragenter',
		'ondragleave',
		'ondragover',
		'ondragstart',
		'ondrop',
		'ondurationchange',
		'onemptied',
		'onended',
		'onerror',
		'onfocus',
		'onformdata',
		'oninput',
		'oninvalid',
		'onkeydown',
		'onkeypress',
		'onkeyup',
		'onload',
		'onloadeddata',
		'onloadedmetadata',
		'onloadstart',
		'onmousedown',
		'onmouseenter',
		'onmouseleave',
		'onmousemove',
		'onmouseout',
		'onmouseover',
		'onmouseup',
		'onpaste',
		'onpause',
		'onplay',
		'onplaying',
		'onprogress',
		'onratechange',
		'onreset',
		'onresize',
		'onscroll',
		'onsecuritypolicyviolation',
		'onseeked',
		'onseeking',
		'onselect',
		'onslotchange',
		'onstalled',
		'onsubmit',
		'onsuspend',
		'ontimeupdate',
		'ontoggle',
		'onvolumechange',
		'onwaiting',
		'onwheel',
	],
	a: [],
	abbr: [],
	address: [],
	area: [],
	article: [],
	aside: [],
	audio: [],
	b: [],
	base: [],
	bdi: [],
	bdo: [],
	blockquote: [],
	body: [],
	br: [],
	button: [],
	canvas: [],
	caption: [],
	cite: [],
	code: [],
	col: [],
	colgroup: [],
	data: [],
	datalist: [],
	dd: [],
	del: [],
	details: [],
	dfn: [],
	dialog: [],
	dir: [],
	div: [],
	dl: [],
	dt: [],
	em: [],
	embed: [],
	fieldset: [],
	figcaption: [],
	figure: [],
	font: [],
	footer: [],
	form: [],
	frame: [],
	frameset: [],
	h1: [],
	h2: [],
	h3: [],
	h4: [],
	h5: [],
	h6: [],
	head: [],
	header: [],
	hgroup: [],
	hr: [],
	html: [],
	i: [],
	iframe: [],
	img: [],
	input: [],
	ins: [],
	kbd: [],
	label: [],
	legend: [],
	li: [],
	link: [],
	main: [],
	map: [],
	mark: [],
	marquee: [],
	menu: [],
	meta: [],
	meter: [],
	nav: [],
	noscript: [],
	object: [],
	ol: [],
	optgroup: [],
	option: [],
	output: [],
	p: [],
	param: [],
	picture: [],
	pre: [],
	progress: [],
	q: [],
	rp: [],
	rt: [],
	ruby: [],
	s: [],
	samp: [],
	script: [],
	section: [],
	select: [],
	slot: [],
	small: [],
	source: [],
	span: [],
	strong: [],
	style: [],
	sub: [],
	summary: [],
	sup: [],
	table: [],
	tbody: [],
	td: [],
	template: [],
	textarea: [],
	tfoot: [],
	th: [],
	thead: [],
	time: [],
	title: [],
	tr: [],
	track: [],
	u: [],
	ul: [],
	var: [],
	video: [],
	wbr: [],
} as const;

export default htmlElementAttributes;
